# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/julien/Desktop/MutaFrame/Hackathon/mmtf-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/julien/Desktop/MutaFrame/Hackathon/mmtf-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julien/Desktop/MutaFrame/Hackathon/mmtf-c/CMakeFiles /home/julien/Desktop/MutaFrame/Hackathon/mmtf-c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/julien/Desktop/MutaFrame/Hackathon/mmtf-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named helloDemo

# Build rule for target.
helloDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloDemo
.PHONY : helloDemo

# fast build rule for target.
helloDemo/fast:
	$(MAKE) -f CMakeFiles/helloDemo.dir/build.make CMakeFiles/helloDemo.dir/build
.PHONY : helloDemo/fast

#=============================================================================
# Target rules for targets named array_decoders

# Build rule for target.
array_decoders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 array_decoders
.PHONY : array_decoders

# fast build rule for target.
array_decoders/fast:
	$(MAKE) -f src/CMakeFiles/array_decoders.dir/build.make src/CMakeFiles/array_decoders.dir/build
.PHONY : array_decoders/fast

#=============================================================================
# Target rules for targets named num_converters

# Build rule for target.
num_converters: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 num_converters
.PHONY : num_converters

# fast build rule for target.
num_converters/fast:
	$(MAKE) -f src/CMakeFiles/num_converters.dir/build.make src/CMakeFiles/num_converters.dir/build
.PHONY : num_converters/fast

#=============================================================================
# Target rules for targets named test_num_converters

# Build rule for target.
test_num_converters: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_num_converters
.PHONY : test_num_converters

# fast build rule for target.
test_num_converters/fast:
	$(MAKE) -f tests/CMakeFiles/test_num_converters.dir/build.make tests/CMakeFiles/test_num_converters.dir/build
.PHONY : test_num_converters/fast

src/demo.o: src/demo.c.o
.PHONY : src/demo.o

# target to build an object file
src/demo.c.o:
	$(MAKE) -f CMakeFiles/helloDemo.dir/build.make CMakeFiles/helloDemo.dir/src/demo.c.o
.PHONY : src/demo.c.o

src/demo.i: src/demo.c.i
.PHONY : src/demo.i

# target to preprocess a source file
src/demo.c.i:
	$(MAKE) -f CMakeFiles/helloDemo.dir/build.make CMakeFiles/helloDemo.dir/src/demo.c.i
.PHONY : src/demo.c.i

src/demo.s: src/demo.c.s
.PHONY : src/demo.s

# target to generate assembly for a file
src/demo.c.s:
	$(MAKE) -f CMakeFiles/helloDemo.dir/build.make CMakeFiles/helloDemo.dir/src/demo.c.s
.PHONY : src/demo.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... helloDemo"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... array_decoders"
	@echo "... num_converters"
	@echo "... test_num_converters"
	@echo "... src/demo.o"
	@echo "... src/demo.i"
	@echo "... src/demo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

